Do not define `HAVE_CLOCK_GETTIME_MONOTONIC` on macOS, use `HAVE_MACH_ABSOLUTE_TIME` instead (#314)
`clock_gettime` wasn't added until macOS 10.12, which causes `dyld: Symbol not found: _clock_gettime` error